ui: jasmine2
browsers:
  - name: chrome
    version: [latest, dev, beta]
  - name: ie
    version: 9..latest
  - name: firefox
    version: [latest, dev, beta]
  - name: safari
    version: 7..latest
  - name: opera
    version: 11..latest
  - name: iphone
    version: 7.1..latest
  - name: android
    version: [4.1,latest]

browserify:
  - transform: coffeeify
  - transform: brfs
  - options:
      extensions:
        - .js
        - .json
        - .coffee
  - exclude: jpeg-js
  - exclude: pngparse
  - exclude: request